apiVersion: v1
kind: Secret
metadata:
  name: blog-api-secret
  labels:
    app: blog-api
type: Opaque
stringData:
  # ----------------------------------------------------
  # Database
  # ----------------------------------------------------
  DATABASE_USERNAME: "my-db-username"
  DATABASE_PASSWORD: "my-super-secret-db-password"

  # ----------------------------------------------------
  # OAuth2
  # ----------------------------------------------------
  SPRING_OAUTH_GOOGLE_CLIENT_ID: "your-google-client-id"
  SPRING_OAUTH_GOOGLE_CLIENT_SECRET: "your-google-client-secret"

  # ----------------------------------------------------
  # ReCAPTCHA
  # ----------------------------------------------------
  GOOGLE_RECAPTCHA_V2_SECRET_KEY: "your-recaptcha-v2-secret-key"
  GOOGLE_RECAPTCHA_V3_SECRET_KEY: "your-recaptcha-v3-secret-key"

  # ----------------------------------------------------
  # JWT
  # ----------------------------------------------------
  JWT_SECRET: "your-jwt-secret-key"

  # ----------------------------------------------------
  # Mailgun
  # ----------------------------------------------------
  MAILGUN_USERNAME: "your-mailgun-username"
  MAILGUN_PASSWORD: "your-mailgun-password"

  # ----------------------------------------------------
  # Cloudflare R2 Storage
  # ----------------------------------------------------
  R2_ACCESS_KEY_ID: "your-r2-access-key-id"
  R2_SECRET_ACCESS_KEY: "your-r2-secret-access-key"
  R2_ENDPOINT: "your-r2-endpoint-url"
  R2_BUCKET_NAME: "your-r2-bucket-name"
  R2_PUBLIC_URL: "your-r2-public-url"