apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blog-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    # apex(contentria.com) 접속 시 www.contentria.com으로 리다이렉트
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - www.contentria.com
        - contentria.com
      secretName: contentria-tls-secret
  rules:
    - host: www.contentria.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: blog-api-service
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: blog-frontend-service
                port:
                  number: 80
    - host: contentria.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: blog-frontend-service
                port:
                  number: 80