apiVersion: v1
kind: ConfigMap
metadata:
  name: blog-batch-config
  labels:
    app: blog-batch
data:
  TZ: "Asia/Seoul"
  SPRING_PROFILES_ACTIVE: "prod"
  DATABASE_URL: "jdbc:postgresql://postgresql.databases.svc.cluster.local:5432/postgres?currentSchema=contentria"
