apiVersion: v1
kind: Secret
metadata:
  name: blog-batch-secret
  namespace: default
type: Opaque
stringData:
  # ----------------------------------------------------
  # Database
  # ----------------------------------------------------
  DATABASE_USERNAME: "my-db-username"
  DATABASE_PASSWORD: "my-super-secret-db-password"