apiVersion: v1
kind: ConfigMap
metadata:
  name: blog-api-config
  labels:
    app: blog-api
data:
  # ----------------------------------------------------
  # 애플리케이션 동작 환경
  # ----------------------------------------------------
  SPRING_PROFILES_ACTIVE: "prod"
  TZ: "Asia/Seoul"

  # ----------------------------------------------------
  # CORS 및 Auth
  # ----------------------------------------------------
  APP_CORS_ALLOWED_ORIGINS: "https://www.contentria.com,https://contentria.com"
  APP_AUTH_OIDC_SUCCESS_REDIRECT_URL: "https://www.contentria.com/login/callback"
  APP_AUTH_RECAPTCHA_EXPECTED_HOSTNAME: "contentria.com"
  COOKIE_SECURE: "true"

  # ----------------------------------------------------
  # 인프라 연결 정보
  # ----------------------------------------------------
  DATABASE_URL: "jdbc:postgresql://postgresql.databases.svc.cluster.local:5432/postgres?currentSchema=contentria"
  MAILGUN_HOST: "smtp.mailgun.org"
  MAILGUN_PORT: "587"
  MAILGUN_DOMAIN: "contentria.com"