CREATE TABLE users (
    id UUID PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    real_username VARCHAR(100),
    username VARCHAR(100),
    nickname VARCHAR(50) NOT NULL UNIQUE,
    picture_url TEXT,
    status VARCHAR(50) NOT NULL DEFAULT 'UNVERIFIED', -- 'ACTIVE', 'UNVERIFIED', 'SUSPENDED', 'DELETED'
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_users_username ON users(username);